language: node_js

# build matrix for testing tasks

os:
  - linux
  - osx

node_js:
  - "node" # latest stable Node.js release
  - "7"

install:
  - npm install

script:
  - ./node_modules/.bin/gulp ci:test

# build on specific version for deployment task

matrix:
  include:
    - os: linux
      node_js: "7.6.0"
      before_install: |
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          echo "Branch is master and it is not pull request, starting deployment"
        else
          echo "Branch is not master or it is pull request, deployment skipped"
          exit 1
        fi
      script:
        ./node_modules/.bin/gulp ci:deploy
